version: '3'
services:
  proxy:
    build: .
    container_name: proxy
    ports:
      - "50051:50051"
    networks:
      - my_network
    depends_on:
      - db


  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    container_name: db
    ports:
      - "5432:5432"
    networks:
      - my_network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - my_network


networks:
  my_network:
    external: true
