// Code generated by mockery v2.35.4. DO NOT EDIT.

package mocks

import (
	models "proxy/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// Storager is an autogenerated mock type for the Storager type
type Storager struct {
	mock.Mock
}

// Add provides a mock function with given fields: response
func (_m *Storager) Add(response models.Response) error {
	ret := _m.Called(response)

	var r0 error
	if rf, ok := ret.Get(0).(func(models.Response) error); ok {
		r0 = rf(response)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Healthcheck provides a mock function with given fields:
func (_m *Storager) Healthcheck() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewStorager creates a new instance of Storager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorager(t interface {
	mock.TestingT
	Cleanup(func())
}) *Storager {
	mock := &Storager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
